- name: ANSISTRANO | RSYNC | Get shared path (in rsync case)
  set_fact:
    ansistrano_shared_rsync_copy_path: "{{ ansistrano_shared_path }}/.shared-copy"

- name: ANSISTRANO | RSYNC | Rsync application files to remote shared copy
  synchronize:
    src: "{{ ansistrano_deploy_from }}"
    dest: "{{ ansistrano_shared_rsync_copy_path }}"
    set_remote_user: "{{ ansistrano_rsync_set_remote_user }}"
    recursive: yes
    delete: yes
    archive: yes
    compress: yes
    use_ssh_args: "{{ ansistrano_rsync_use_ssh_args | default(omit) }}"
    rsync_opts: "{{ ansistrano_rsync_extra_params | default(omit) }}"
    rsync_path: "{{ ansistrano_rsync_path | default(omit) }}"

- name: ANSISTRANO | RSYNC | Deploy existing code to servers
  copy:
    src: "{{ ansistrano_shared_rsync_copy_path }}/"
    dest: "{{ ansistrano_release_path.stdout }}/"
    remote_src: yes
