name: Ansible Tests

on:
  push:
    branches: [ "main", "mdurand/WIP" ]
  pull_request:
    branches: [ "main", "mdurand/WIP" ]

jobs:
  ansible-tests:
    runs-on: ubuntu-latest
    env:
      COMPOSE_DOCKER_CLI_BUILD: 1
      DOCKER_BUILDKIT: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: docker compose -f docker-compose.yml build

      - name: Start all containers
        run: docker compose -f docker-compose.yml up -d

      - name: Wait for SSH to be ready
        run: |
          echo "Waiting for SSH in amazonlinux..."
          until docker exec ansistrano_amazonlinux ssh -o StrictHostKeyChecking=no root@localhost echo "ok"; do sleep 2; done
          # répétez pour les autres OS si nécessaire

      - name: Run Ansible tests
        run: |
          for os in amazonlinux debian fedora opensuse rockylinux ubuntu; do
            echo "Running tests on $os..."
            docker exec ansistrano ansible-playbook /app/test/main.yml -i /app/test/hosts.yml
          done

      - name: Tear down containers
        if: always()
        run: docker compose -f docker-compose.yml down --remove-orphans
